"""Cursor Handshake — delegate complex repairs to the Cursor IDE agent.

Writes a markdown implementation plan to ``CAMGRASPER/cursor_handoffs/donna_handoff.md``
(mirrored into project ``.cursor/instructions/``) and optionally launches Cursor /
alerts the user via TTS. Never hot-patches core source from this path.
"""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from donna.bug_tracker import open_bugs
from donna.paths import (
    CURSOR_HANDOFF_DIR,
    CURSOR_HANDOFF_PATH,
    DONNA_WORKSPACE,
    PENDING_PATCHES_DIR,
    PROJECT_ROOT,
)

HANDOFF_DIR = CURSOR_HANDOFF_DIR
HANDOFF_PATH = CURSOR_HANDOFF_PATH


def _pending_patch_summaries(limit: int = 5) -> list[str]:
    if not PENDING_PATCHES_DIR.is_dir():
        return []
    files = sorted(PENDING_PATCHES_DIR.glob("*.json"), reverse=True)
    out: list[str] = []
    for path in files[:limit]:
        if path.name.upper() == "README.MD":
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        out.append(f"- `{path.name}` ({len(text)} chars)")
    return out


def build_handoff_markdown(
    *,
    query: str = "",
    error: str = "",
    context: str = "",
    goal: str = "",
) -> str:
    bugs = open_bugs()
    bug_lines: list[str] = []
    for bug in bugs[:8]:
        bug_lines.append(
            f"- **{bug.get('id') or 'bug'}** ({bug.get('status')}): "
            f"`{(bug.get('error') or '')[:200]}`"
        )
    if not bug_lines:
        bug_lines = [
            "- (no PENDING bugs in CAMGRASPER/tracker/bug_tracker.json)"
        ]

    patches = _pending_patch_summaries()
    patch_block = "\n".join(patches) if patches else "- (none yet)"
    tracker = DONNA_WORKSPACE / "tracker"

    stamp = datetime.now(timezone.utc).isoformat()
    goal_text = (goal or query or "Repair the failing Donna agent path.").strip()
    err = (error or "").strip()
    ctx = (context or "").strip()

    return f"""# Donna → Cursor Handoff

> Auto-generated by `delegate_to_cursor` at {stamp}.
> Canonical path: `{HANDOFF_PATH}`
> Mirrored for Cursor: `.cursor/instructions/donna_handoff.md`
> **Do not apply blindly** — review, then instruct the Cursor agent (Grok / Composer) to execute.

## Objective

{goal_text}

## User / agent context

```
{(query or ctx or '(none)')[:4000]}
```

## Isolated failure

```
{(err or ctx or '(see bug tracker)')[:4000]}
```

## PENDING bugs (Autonomous Bug Tracker)

{chr(10).join(bug_lines)}

## Existing Titan drafts

Review these under `{tracker / "pending_patches"}` before rewriting:

{patch_block}

## Implementation plan for Cursor

1. Open the CAMGRASPER workspace root.
2. Read `tracker/bug_tracker.json` and the latest file in
   `tracker/pending_patches/`.
3. Reproduce the failure with the headless harness if applicable:
   `python -m donna.evals.headless_harness`
4. Apply a **minimal** fix to the implicated module(s); prefer tests in
   `tests/` / `donna/evals/`.
5. Do **not** weaken Tool Forge AST / security gates or production sandbox locks.
6. Re-run focused unit tests, then the headless harness Pass@k suite.
7. Summarize the diff and residual risks for the user.

## Acceptance criteria

- [ ] Failure no longer reproduces in headless eval / targeted unit test
- [ ] No new Tier-3 imports or native `open()` in forged/generated tools
- [ ] Bug tracker entry marked resolved or patched after human review
- [ ] Voice loop no longer speaks raw JSON or crashes on missing vault keys

## How to run

In Cursor chat, tell the agent:

> Execute the implementation plan in `.cursor/instructions/donna_handoff.md`
> (same content as `cursor_handoffs/donna_handoff.md`).

---
*Donna Tool Forge / Titan Repair will not hot-patch core source without your approval.*
"""


def write_handoff_file(
    *,
    query: str = "",
    error: str = "",
    context: str = "",
    goal: str = "",
) -> Path:
    HANDOFF_DIR.mkdir(parents=True, exist_ok=True)
    body = build_handoff_markdown(
        query=query, error=error, context=context, goal=goal
    )
    HANDOFF_PATH.write_text(body, encoding="utf-8")
    try:
        from donna.workspace import ensure_cursor_handoff_mirror

        ensure_cursor_handoff_mirror()
    except Exception:
        pass
    return HANDOFF_PATH


def _try_launch_cursor() -> str:
    """Best-effort: open the workspace in Cursor (optional)."""
    if os.environ.get("DONNA_CURSOR_LAUNCH", "1").strip().lower() in (
        "0",
        "false",
        "no",
        "off",
    ):
        return "launch_skipped"
    root = str(PROJECT_ROOT)
    candidates = [
        ["cursor", root],
        ["cursor.cmd", root],
    ]
    if sys.platform == "win32":
        candidates.append(["cmd", "/c", "cursor", root])
    for cmd in candidates:
        try:
            subprocess.Popen(  # noqa: S603 — allowlisted cursor launcher
                cmd,
                cwd=root,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return f"launched:{cmd[0]}"
        except Exception:
            continue
    return "launch_failed"


def delegate_to_cursor(
    *,
    query: str = "",
    error: str = "",
    context: str = "",
    goal: str = "",
    launch_cursor: bool = True,
    speak: bool = True,
) -> str:
    """Write the handoff plan and optionally open Cursor / TTS-notify the user."""
    path = write_handoff_file(query=query, error=error, context=context, goal=goal)
    launch_note = _try_launch_cursor() if launch_cursor else "launch_skipped"
    tts = (
        "I have written the implementation plan. Please open Cursor and instruct "
        "Grok to execute the donna_handoff file."
    )
    if speak:
        try:
            from donna.core_agent import enqueue_speech

            enqueue_speech(tts)
        except Exception:
            pass
    return (
        f"OK: delegate_to_cursor wrote {path} launch={launch_note}. "
        f"Speak to user: {tts}"
    )


def handle_tool_call(call: Any) -> str:
    args = getattr(call, "arguments", None) or {}
    if not isinstance(args, dict):
        args = {}
    query = str(
        args.get("query") or args.get("goal") or getattr(call, "raw_text", "") or ""
    ).strip()
    return delegate_to_cursor(
        query=query,
        error=str(args.get("error") or ""),
        context=str(args.get("context") or ""),
        goal=str(args.get("goal") or query),
        launch_cursor=str(args.get("launch_cursor") or "true").lower()
        not in ("0", "false", "no"),
    )
